CONCEPTS = ['Centralised', 'Hybrid', 'Decentralised']
UNCERTAINTIES = ['R1', 'R2', 'R3', 'W1', 'W3', 'W5']

CONF_LOG_PREFIX = 'CONFLOG'
FLST_LOG_PREFIX = 'FLSTLOG'
FP_INT_PREFIX = 'Flight_intention'
GEO_LOG_PREFIX = 'GEOLOG'
LOS_LOG_PREFIX = 'LOSLOG'
REG_LOG_PREFIX = 'REGLOG'

LINE_COUNT = 'line_count'

FEET_TO_METERS_SCALE = 0.3048
METERS_TO_FEET_SCALE = 3.280839895
