SCENARIOS = ['Centralised', 'Hybrid', 'Decentralised']

CONF_LOG_PREFIX = 'CONFLOG'
LOS_LOG_PREFIX = 'LOSLOG'
GEO_LOG_PREFIX = 'GEOLOG'
FLST_LOG_PREFIX = 'FLSTLOG'
REG_LOG_PREFIX = 'REGLOG'
FP_INT_PREFIX = 'Flight_intention'
LINE_COUNT = 'line_count'
