SCENARIOS = ['Centralised', 'Hybrid', 'Decentralised']

CONF_LOG_PREFIX = 'CONFLOG'
FLST_LOG_PREFIX = 'FLSTLOG'
FP_INT_PREFIX = 'Flight_intention'
GEO_LOG_PREFIX = 'GEOLOG'
LOS_LOG_PREFIX = 'LOSLOG'
REG_LOG_PREFIX = 'REGLOG'

LINE_COUNT = 'line_count'

FEET_TO_METERS_SCALE = 0.3048
METERS_TO_FEET_SCALE = 39.37
