# PATH
data_path = "/mnt/shared/repos/metropolis/M2_data_analysis_platform/data"
saving_path = "/mnt/shared/repos/metropolis/M2_data_analysis_platform/output"
flight_intention_path = "@format {this.data_path}/Flight_intentions"

# LOGGING
logging.level = "DEBUG"

# SPARK CONFIG
spark.app_name = "M2-Data-Analysis-Platform"

# DRONE CONFIG
MP30.avg_speed = 15.43 # m/s
MP30.autonomy = 1800
MP20.avg_speed = 10.29 # m/s
MP20.autonomy = 1800

# THRESHOLDS
thresholds.destination_distance = 400

# COORDINATE SYSTEM
crs.origin = "epsg:4326"
crs.desired = "epsg:32633"
