# PATH
# Folder path where the logs file are. There should be a folder per concept
# and the folder for the flight intentions. Like:
# data_folder
#   |--- Centralised
#   |--- Decentralised
#   |--- Hybrid
#   |--- Flight_intentions (this one could be in another path)
#
data_path = "../data"
# Path to the flight intentions, uses the data folder as root. However,
# it can be changed to an external folder.
flight_intention_path = "@format {this.data_path}/Flight_intentions"
# Path to the JSON with the interest points to calculate the noise
interest_points = "@format {this.data_path}/interest_points.json"
# Folder where the generated data will be saved. This included the processed
# logs files and the metric dataframes.
saving_path = "../output"

# GEOJSON ENV3 POINTS PATH
geojson.path = "C:\\Users\\jpedrero\\workspace\\M2_data_analysis_platform\\graphs\\env3_points.geojson"


# LOGGING
logging.level = "INFO"

# SPARK CONFIG
spark.app_name = "M2-Data-Analysis-Platform"

# DRONE CONFIG
MP30.avg_speed = 15.43 # m/s
MP30.autonomy = 1800 # seconds
MP30.vertical_speed = 5 # m/s
MP20.avg_speed = 10.29 # m/s
MP20.autonomy = 1800 # seconds
MP20.vertical_speed = 5 # m/s

flight_altitude.loitering = 18.288 # 60 feets
flight_altitude.lowest = 9.144 # 30 feets

# THRESHOLDS
thresholds.destination_distance = 400 # meters
thresholds.delay = 5 # seconds
thresholds.emergency_mission_delay = 300 # seconds
thresholds.delivery_mission_delay = 600 # seconds
thresholds.loitering_mission_delay = 1200 # seconds
thresholds.crash_vertical_distance = 0.749808 # meters = 2.46 feet
thresholds.crash_horizontal_distance = 1.7 # meters
thresholds.intrusion_distance = 1 # meters
threshold.AEQ5 = 50

# WEIGHTS
weights.priority_1 = 1
weights.priority_2 = 2
weights.priority_3 = 4
weights.priority_4 = 8

# COORDINATE SYSTEM
crs.origin = "epsg:4326"
crs.desired = "epsg:32633"

#ROI POINT ENV3
env3.time_roi = 120 # seconds
env3.distance_to_point = 160 # meters
env3.reference_altitude = 9.144 # 30 feets, same as lower layer
